global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: scorestv-prod
    environment: production

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: scorestv-backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['127.0.0.1:8080']
        labels: { service: backend }

  - job_name: node-app
    static_configs:
      - targets: ['127.0.0.1:9100']
        labels: { host: scorestv-app }

  - job_name: node-data
    static_configs:
      - targets: ['10.0.0.3:9100']
        labels: { host: scorestv-data }

  - job_name: postgres
    static_configs:
      - targets: ['10.0.0.3:9187']
        labels: { service: postgres }

  - job_name: redis
    static_configs:
      - targets: ['10.0.0.3:9121']
        labels: { service: redis }

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['10.0.0.3:9000']
        labels: { service: minio }

  - job_name: node-search
    static_configs:
      - targets: ['10.0.0.4:9100']
        labels: { host: scorestv-search }

  - job_name: elasticsearch
    static_configs:
      - targets: ['10.0.0.4:9114']
        labels: { service: elasticsearch }

  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']
