-- ===================================================================
-- V11 - Maç kadroları (lineups) ve içlerindeki oyuncular.
--
-- API-Football /fixtures/lineups: her maç için iki kayıt (ev + deplasman).
-- Her takım için: formasyon, koç, takım renkleri, ilk 11, yedekler.
--
-- Tasarım:
--   fixture_lineups       — takım bazlı 1 satır. UNIQUE(fixture_id,team_id).
--                           announced_at YALNIZ ilk insert'te set edilir,
--                           sonraki sync'ler güncellemez (frontend "kadro
--                           2 saat önce açıklandı" göstergesi için).
--   fixture_lineup_players — kadro içindeki her oyuncu (ilk 11 + yedekler).
--                           Sync'te SİLİNİP yeniden yazılır (replace).
-- ===================================================================

CREATE TABLE fixture_lineups (
    id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id            BIGINT      NOT NULL REFERENCES fixtures (id) ON DELETE CASCADE,
    team_id               BIGINT      NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
    formation             VARCHAR(20),
    coach_id              BIGINT,
    coach_name            VARCHAR(120),
    coach_photo           VARCHAR(255),
    -- Takım renkleri (oyuncu / kaleci × primary/number/border). API hex string.
    player_color_primary  VARCHAR(8),
    player_color_number   VARCHAR(8),
    player_color_border   VARCHAR(8),
    gk_color_primary      VARCHAR(8),
    gk_color_number       VARCHAR(8),
    gk_color_border       VARCHAR(8),
    -- "Kadro açıklandı" zaman damgası — ilk insert'te now(); update'lerde DOKUNULMAZ.
    announced_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fixture_lineups_fixture_team UNIQUE (fixture_id, team_id)
);

CREATE INDEX idx_fixture_lineups_fixture_id ON fixture_lineups (fixture_id);

CREATE TABLE fixture_lineup_players (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lineup_id     BIGINT      NOT NULL REFERENCES fixture_lineups (id) ON DELETE CASCADE,
    -- API-Football player id (FK yok, oyuncu tablosu henüz yok).
    player_id     BIGINT,
    player_name   VARCHAR(120),
    jersey_number INTEGER,
    -- Pozisyon: G (kaleci), D (defans), M (orta), F (forvet).
    position      VARCHAR(5),
    -- Saha üzerindeki konum "X:Y" — X satır, Y sütun. Yedekler için null.
    grid          VARCHAR(10),
    -- false = ilk 11, true = yedek.
    is_substitute BOOLEAN     NOT NULL DEFAULT false,
    -- Display sırası — API'den gelen sıra korunsun diye.
    sort_order    INTEGER     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_fixture_lineup_players_lineup_id ON fixture_lineup_players (lineup_id);
