-- ===================================================================
-- V12 - Maç istatistikleri (takım bazlı).
--
-- API-Football /fixtures/statistics: maç başına 2 satır (ev + deplasman),
-- her satırda ~16 stat (Shots on Goal, Ball Possession "32%", Total passes,
-- Yellow Cards, expected_goals, ...).
--
-- value tipi karışık: Integer (3, 9, 242), String ("32%"), null. Hepsini
-- VARCHAR olarak saklarız; frontend ihtiyaca göre parse eder ("32%" →
-- progress bar, "3" → sayı). Bu, yeni stat tipi eklendiğinde de migration
-- gerektirmez.
--
-- Sync stratejisi: o maçın TÜM stat satırlarını siler, gelenleri yazar
-- (replace pattern — eski tip artık API'da yoksa otomatik düşer).
-- ===================================================================

CREATE TABLE fixture_statistics (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id  BIGINT      NOT NULL REFERENCES fixtures (id) ON DELETE CASCADE,
    team_id     BIGINT      NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
    stat_type   VARCHAR(40) NOT NULL,
    stat_value  VARCHAR(30),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fixture_statistics UNIQUE (fixture_id, team_id, stat_type)
);

CREATE INDEX idx_fixture_statistics_fixture_id ON fixture_statistics (fixture_id);
