-- ===================================================================
-- V13 - Oyuncu bazli mac istatistikleri.
--
-- API-Football /fixtures/players: mac basina 2 ana oge (ev/deplasman),
-- her ogenin players[] icinde takim basina ~14-20 oyuncu, her oyuncuda
-- "statistics" array'i (her zaman 1 elemanli — games/shots/goals/passes
-- /tackles/duels/dribbles/fouls/cards/penalty bloklari).
--
-- Saklama: flat sutunlar — JSON yerine acik sema. Boylece "X oyuncunun
-- son 10 macindaki ortalama rating" gibi sorgular DB tarafinda calisir.
--
-- rating ve passes_accuracy: API string ("7.2", "60") — VARCHAR olarak
-- saklarsak format kayboldugu yerlerde de calisir.
--
-- penalty_committed: API'de "commited" (typo) ile gelir; DB'de dogru
-- yazimla saklarsiz, mapper esler.
--
-- Sync replace pattern: o macin tum oyuncu istatistikleri silinip yeniden
-- yazilir. UNIQUE(fixture, player) ile cift kayit korur.
-- ===================================================================

CREATE TABLE fixture_player_stats (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id          BIGINT      NOT NULL REFERENCES fixtures (id) ON DELETE CASCADE,
    team_id             BIGINT      NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
    player_id           BIGINT,
    player_name         VARCHAR(120),
    player_photo        VARCHAR(255),

    -- games bloku
    minutes             INTEGER,
    jersey_number       INTEGER,
    position            VARCHAR(5),
    rating              VARCHAR(8),
    captain             BOOLEAN,
    substitute          BOOLEAN,

    -- tek alanlar
    offsides            INTEGER,

    -- shots
    shots_total         INTEGER,
    shots_on            INTEGER,

    -- goals
    goals_total         INTEGER,
    goals_conceded      INTEGER,
    goals_assists       INTEGER,
    goals_saves         INTEGER,

    -- passes
    passes_total        INTEGER,
    passes_key          INTEGER,
    passes_accuracy     VARCHAR(8),

    -- tackles
    tackles_total       INTEGER,
    tackles_blocks      INTEGER,
    tackles_interceptions INTEGER,

    -- duels
    duels_total         INTEGER,
    duels_won           INTEGER,

    -- dribbles
    dribbles_attempts   INTEGER,
    dribbles_success    INTEGER,
    dribbles_past       INTEGER,

    -- fouls
    fouls_drawn         INTEGER,
    fouls_committed     INTEGER,

    -- cards
    cards_yellow        INTEGER,
    cards_red           INTEGER,

    -- penalty
    penalty_won         INTEGER,
    penalty_committed   INTEGER,
    penalty_scored      INTEGER,
    penalty_missed      INTEGER,
    penalty_saved       INTEGER,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_fixture_player_stats UNIQUE (fixture_id, player_id)
);

CREATE INDEX idx_fixture_player_stats_fixture_id ON fixture_player_stats (fixture_id);
CREATE INDEX idx_fixture_player_stats_player_id  ON fixture_player_stats (player_id);
