-- ===================================================================
-- V14 - Sakatlık / cezalı oyuncu listesi (fixture bazında).
--
-- API-Football /injuries?fixture={id}: o maca katilamayacak veya
-- supheli oyuncular. Tip "Missing Fixture" veya "Questionable".
--
-- API quirk: response'ta type ve reason "player" objesinin ICINDE gelir
-- (top-level degil) — upserter buna gore mapler.
--
-- Sync stratejisi: o macin tum injury satirlari silinip yeniden yazilir
-- (replace) — bir oyuncu artik listede degilse otomatik duser.
-- ===================================================================

CREATE TABLE injuries (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id   BIGINT      NOT NULL REFERENCES fixtures (id) ON DELETE CASCADE,
    team_id      BIGINT      NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
    -- API-Football player id (FK yok, oyuncu tablosu henuz yok).
    player_id    BIGINT,
    player_name  VARCHAR(120),
    player_photo VARCHAR(255),
    -- "Missing Fixture" (oynayamayacak) | "Questionable" (supheli).
    type         VARCHAR(40),
    -- "Broken ankle", "Illness", "Suspended", "Knock"...
    reason       VARCHAR(120),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_injuries_fixture_id ON injuries (fixture_id);
