-- ===================================================================
-- V6 - API-Football veri şeması (futbol verisi aynası)
--
-- Veriler API-Football'dan zamanlanmış senkron işleriyle bu tablolara
-- aynalanır; uygulama her zaman bu tablolardan okur. Aynalanan varlıklar
-- (venues, leagues, teams, fixtures) API-Football'un kendi ID'lerini
-- birincil anahtar olarak kullanır; böylece senkron upsert'leri sadedir.
-- ===================================================================

-- Stadyumlar -----------------------------------------------------------
CREATE TABLE venues (
    id         BIGINT       PRIMARY KEY,          -- API-Football venue id
    name       VARCHAR(150) NOT NULL,
    address    VARCHAR(255),
    city       VARCHAR(120),
    capacity   INTEGER,
    surface    VARCHAR(50),
    image_url  VARCHAR(255),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Ligler / kupalar -----------------------------------------------------
CREATE TABLE leagues (
    id               BIGINT       PRIMARY KEY,    -- API-Football league id
    name             VARCHAR(150) NOT NULL,
    type             VARCHAR(20),                 -- 'League' | 'Cup'
    logo_url         VARCHAR(255),
    country_name     VARCHAR(100),
    country_code     VARCHAR(10),
    country_flag_url VARCHAR(255),
    current_season   INTEGER,                     -- geçerli sezon yılı
    covered          BOOLEAN      NOT NULL DEFAULT FALSE,  -- senkron kapsamında mı
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_leagues_covered ON leagues (covered);

-- Takımlar -------------------------------------------------------------
CREATE TABLE teams (
    id         BIGINT       PRIMARY KEY,          -- API-Football team id
    name       VARCHAR(150) NOT NULL,
    code       VARCHAR(10),
    country    VARCHAR(100),
    founded    INTEGER,
    national   BOOLEAN      NOT NULL DEFAULT FALSE,
    logo_url   VARCHAR(255),
    venue_id   BIGINT       REFERENCES venues (id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_teams_venue_id ON teams (venue_id);

-- Maçlar (fikstür) -----------------------------------------------------
CREATE TABLE fixtures (
    id             BIGINT      PRIMARY KEY,        -- API-Football fixture id
    league_id      BIGINT      NOT NULL REFERENCES leagues (id),
    season         INTEGER     NOT NULL,
    round          VARCHAR(100),
    home_team_id   BIGINT      NOT NULL REFERENCES teams (id),
    away_team_id   BIGINT      NOT NULL REFERENCES teams (id),
    venue_id       BIGINT      REFERENCES venues (id) ON DELETE SET NULL,
    referee        VARCHAR(120),
    kickoff_at     TIMESTAMPTZ NOT NULL,          -- maç başlangıç zamanı
    status_short   VARCHAR(10) NOT NULL,          -- NS, 1H, HT, 2H, FT, PST...
    status_long    VARCHAR(50),
    elapsed        INTEGER,                       -- canlı dakika
    home_goals     INTEGER,
    away_goals     INTEGER,
    score_ht_home  INTEGER,                       -- ilk yarı
    score_ht_away  INTEGER,
    score_ft_home  INTEGER,                       -- normal süre sonu
    score_ft_away  INTEGER,
    score_et_home  INTEGER,                       -- uzatma
    score_et_away  INTEGER,
    score_pen_home INTEGER,                       -- penaltılar
    score_pen_away INTEGER,
    last_synced_at TIMESTAMPTZ,                   -- API'den en son ne zaman çekildi
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_fixtures_kickoff_at     ON fixtures (kickoff_at);
CREATE INDEX idx_fixtures_status_short   ON fixtures (status_short);
CREATE INDEX idx_fixtures_league_season  ON fixtures (league_id, season);
CREATE INDEX idx_fixtures_home_team_id   ON fixtures (home_team_id);
CREATE INDEX idx_fixtures_away_team_id   ON fixtures (away_team_id);

-- Maç olayları (gol, kart, değişiklik) - maç detayı zaman çizelgesi -----
CREATE TABLE fixture_events (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id   BIGINT      NOT NULL REFERENCES fixtures (id) ON DELETE CASCADE,
    team_id      BIGINT      REFERENCES teams (id) ON DELETE SET NULL,
    time_elapsed INTEGER     NOT NULL,
    time_extra   INTEGER,
    type         VARCHAR(30) NOT NULL,            -- Goal, Card, subst, Var
    detail       VARCHAR(60),
    comments     VARCHAR(120),
    player_id    BIGINT,                          -- API-Football player id (FK yok)
    player_name  VARCHAR(120),
    assist_id    BIGINT,
    assist_name  VARCHAR(120),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_fixture_events_fixture_id ON fixture_events (fixture_id);

-- Puan durumu ----------------------------------------------------------
CREATE TABLE standings (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id     BIGINT       NOT NULL REFERENCES leagues (id) ON DELETE CASCADE,
    season        INTEGER      NOT NULL,
    team_id       BIGINT       NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
    rank          INTEGER      NOT NULL,
    group_name    VARCHAR(80),
    points        INTEGER      NOT NULL,
    goals_diff    INTEGER,
    form          VARCHAR(100),
    description   VARCHAR(150),
    played        INTEGER,
    win           INTEGER,
    draw          INTEGER,
    lose          INTEGER,
    goals_for     INTEGER,
    goals_against INTEGER,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_standings_league_season_team UNIQUE (league_id, season, team_id)
);

CREATE INDEX idx_standings_league_season ON standings (league_id, season);
