-- ===================================================================
-- V7 - Referans veri: ülkeler ve lig sezonları
--
-- Nadiren değişen statik veri. /countries ve /leagues senkronlarıyla
-- önden DB'ye alınır; böylece bu bilgi için sürekli API'ye gidilmez.
-- ===================================================================

-- Ülkeler --------------------------------------------------------------
-- API-Football'un ülke kodu bazı kayıtlarda (örn. "World") null olabildiği
-- için birincil anahtar üretilen id; ad ise benzersizdir.
CREATE TABLE countries (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    code       VARCHAR(10),
    flag_url   VARCHAR(255),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_countries_name UNIQUE (name)
);

-- Lig sezonları --------------------------------------------------------
-- Her lig için bir veya daha fazla sezon. /leagues yanıtında her ligin
-- altında gömülü gelir. (lig, yıl) ikilisi benzersizdir.
CREATE TABLE seasons (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id   BIGINT      NOT NULL REFERENCES leagues (id) ON DELETE CASCADE,
    season_year INTEGER     NOT NULL,
    start_date  DATE,
    end_date    DATE,
    is_current  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_seasons_league_year UNIQUE (league_id, season_year)
);

CREATE INDEX idx_seasons_league_id ON seasons (league_id);
